"""Figures (base64 PNG) generated by run_python must appear in chat export files.

Previously /api/export/report/from-chat (markdown) + /api/export/notebook/from-chat
(ipynb) never read action.tool_result.figures, so downloaded .md / .ipynb files
contained no CMD / light curve / phase-fold plots. This test locks the fix:

- markdown: figures embedded as ![Figure N](data:image/png;base64,...)
- notebook: figures written into cell.outputs as display_data PNG, with
  stdout also written as a stream output, so the .ipynb renders directly in
  Jupyter / VSCode / GitHub / Colab / nbviewer (no re-run needed — re-running
  would fail anyway since astro.* helpers are not available in a plain Jupyter kernel).
"""

from __future__ import annotations

import base64
import json

from fastapi.testclient import TestClient


def _client() -> TestClient:
    import app.main as main_mod
    return TestClient(main_mod.app)


# A 1x1 transparent PNG in base64. Tests only care about byte pass-through, not image content.
_TINY_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="
)


def _sample_messages_with_figure() -> list[dict]:
    """Simulate a single assistant message containing a run_python action with stdout + 1 figure."""
    return [
        {"role": "user", "content": "Plot the CMD."},
        {
            "role": "assistant",
            "content": "Here is the CMD.",
            "actions": [
                {
                    "action": "run_python",
                    "tool_input": {"code": "import matplotlib.pyplot as plt\nplt.plot([1,2,3])\nplt.show()"},
                    "tool_result": {
                        "success": True,
                        "stdout": "Plot saved.\n",
                        "figures": [_TINY_PNG_B64],
                        "variables": {},
                    },
                },
            ],
        },
    ]


def test_markdown_export_embeds_run_python_figures_as_data_uri() -> None:
    """Markdown export must embed figures as data:image/png;base64 URIs,
    so the .md file renders inline in VS Code / Typora / Obsidian / GitHub
    without needing a separate zip of PNG files."""
    client = _client()
    resp = client.post(
        "/api/export/report/from-chat",
        json={"messages": _sample_messages_with_figure(), "title": "Pleiades"},
    )
    assert resp.status_code == 200, resp.text
    body = resp.text

    # Figure must appear as a markdown image with a data URI
    # PART AI: caption is "Figure {py_cell_idx}.{fig_idx}" for multi-cell friendliness.
    assert "![Figure 1.1](data:image/png;base64," in body, (
        "Markdown export missing inline figure; figures field on tool_result "
        "was dropped. Body sample: " + body[:500]
    )
    # The real base64 bytes must be passed through unchanged (not truncated or replaced by a placeholder)
    assert _TINY_PNG_B64 in body
    # stdout should also be preserved so users can see printed values
    assert "Plot saved." in body


def test_markdown_export_handles_full_data_uri_and_bare_base64() -> None:
    """The frontend sometimes stores figures as 'data:image/png;base64,XXX', sometimes as
    bare base64. Both forms must be handled."""
    client = _client()
    msgs = [
        {
            "role": "assistant",
            "content": "two figs",
            "actions": [{
                "action": "run_python",
                "tool_input": {"code": "pass"},
                "tool_result": {
                    "success": True,
                    "figures": [
                        f"data:image/png;base64,{_TINY_PNG_B64}",  # full URI
                        _TINY_PNG_B64,                              # bare base64
                    ],
                },
            }],
        }
    ]
    resp = client.post("/api/export/report/from-chat", json={"messages": msgs, "title": "t"})
    assert resp.status_code == 200
    body = resp.text
    # Both figures must appear with the correct data URI prefix.
    # Both figures come from the same run_python (cell #1) and are numbered 1.1 and 1.2.
    assert body.count("![Figure 1.1](data:image/png;base64,") == 1
    assert body.count("![Figure 1.2](data:image/png;base64,") == 1


def test_notebook_export_writes_figures_to_cell_outputs() -> None:
    """Notebook export must write figures into cell.outputs as display_data PNG,
    so the .ipynb renders figures immediately in Jupyter / VSCode / GitHub / Colab
    without 'Run All' (re-running would fail anyway since astro.* helpers are not
    available in a plain kernel)."""
    client = _client()
    resp = client.post(
        "/api/export/notebook/from-chat",
        json={"messages": _sample_messages_with_figure(), "title": "Pleiades"},
    )
    assert resp.status_code == 200, resp.text
    nb = json.loads(resp.text)
    assert nb["nbformat"] == 4

    # Locate the code cell produced by run_python
    code_cells = [c for c in nb["cells"] if c["cell_type"] == "code"]
    # The first code cell is the helper imports (D6.1); skip it, take subsequent cells with outputs
    code_with_outputs = [c for c in code_cells if c.get("outputs")]
    assert len(code_with_outputs) >= 1, (
        "No code cell carries outputs; figures got dropped during export. "
        f"Got {len(code_cells)} code cells, none with outputs."
    )

    target = code_with_outputs[0]
    outputs = target["outputs"]

    # outputs must contain at least one image/png display_data entry
    image_outputs = [
        o for o in outputs
        if o.get("output_type") == "display_data"
        and isinstance(o.get("data"), dict)
        and "image/png" in o["data"]
    ]
    assert len(image_outputs) == 1, (
        f"Expected exactly 1 image/png display_data output; got "
        f"{len(image_outputs)}. outputs: {outputs}"
    )
    assert image_outputs[0]["data"]["image/png"] == _TINY_PNG_B64

    # stdout should also be present as a stream output
    stdout_outputs = [
        o for o in outputs
        if o.get("output_type") == "stream" and o.get("name") == "stdout"
    ]
    assert len(stdout_outputs) == 1
    assert "Plot saved." in stdout_outputs[0]["text"]

    # execution_count should be set to a non-None value (indicating the cell appears to have been run)
    assert target.get("execution_count") is not None


def test_notebook_export_strips_data_uri_prefix_for_image_png() -> None:
    """The Jupyter standard requires display_data['image/png'] to be bare base64 without
    the 'data:image/png;base64,' prefix. Both input forms must be normalized."""
    client = _client()
    msgs = [
        {
            "role": "assistant",
            "content": "fig",
            "actions": [{
                "action": "run_python",
                "tool_input": {"code": "pass"},
                "tool_result": {
                    "success": True,
                    "figures": [f"data:image/png;base64,{_TINY_PNG_B64}"],
                },
            }],
        }
    ]
    resp = client.post("/api/export/notebook/from-chat", json={"messages": msgs, "title": "t"})
    assert resp.status_code == 200
    nb = json.loads(resp.text)
    code_with_outputs = [c for c in nb["cells"] if c["cell_type"] == "code" and c.get("outputs")]
    img = code_with_outputs[0]["outputs"][0]["data"]["image/png"]
    # The prefix must be stripped
    assert not img.startswith("data:")
    assert img == _TINY_PNG_B64
    # Must be decodable as base64 (sanity check against corrupted data)
    base64.b64decode(img)


def test_markdown_export_skips_empty_figures_gracefully() -> None:
    """A run_python action with no figures should not error or leave an empty ![Figure 0] placeholder."""
    client = _client()
    msgs = [
        {
            "role": "assistant",
            "content": "no plot",
            "actions": [{
                "action": "run_python",
                "tool_input": {"code": "print('hi')"},
                "tool_result": {"success": True, "stdout": "hi\n", "figures": []},
            }],
        }
    ]
    resp = client.post("/api/export/report/from-chat", json={"messages": msgs, "title": "t"})
    assert resp.status_code == 200
    body = resp.text
    assert "data:image/png" not in body
    assert "hi" in body  # stdout still preserved


def test_markdown_export_drops_action_dump_for_non_python_tools() -> None:
    """PART AI: Previously every action emitted '### Action: xxx' + full params dict,
    causing long sessions to balloon to 100+ pages. After switching to a one-line
    summary, 200 rows of run_adql results must not appear in the markdown."""
    client = _client()

    # Simulate a run_adql action whose result contains 200 rows of real data + columns
    fake_rows = [{"ra": float(i), "dec": float(i)} for i in range(200)]
    msgs = [
        {
            "role": "assistant",
            "content": "Queried Gaia.",
            "actions": [
                {
                    "action": "run_adql",
                    "tool_input": {"query": "SELECT TOP 200 ra, dec FROM gaia"},
                    "tool_result": {
                        "row_count": 200,
                        "columns": ["ra", "dec"],
                        "data": fake_rows,
                    },
                }
            ],
        }
    ]
    resp = client.post("/api/export/report/from-chat", json={"messages": msgs, "title": "t"})
    assert resp.status_code == 200
    body = resp.text

    # Must have a one-line summary including row_count
    assert "200 rows" in body
    assert "run_adql" in body
    # Raw 200-row data must not be dumped into the output
    assert '{"ra": 199.0' not in body
    assert "ra: 199" not in body
    # Old "### Action:" header must not appear
    assert "### Action:" not in body
    # Overall length should be < 1000 chars (single action + short message)
    assert len(body) < 2000, f"Markdown body too verbose: {len(body)} bytes"


def test_markdown_export_truncates_huge_stdout() -> None:
    """A single run_python printing 5000 lines must not blow up the export. Truncate to head/tail."""
    client = _client()
    huge_stdout = "\n".join(f"line {i}" for i in range(5000))
    msgs = [
        {
            "role": "assistant",
            "content": "x",
            "actions": [{
                "action": "run_python",
                "tool_input": {"code": "for i in range(5000): print(...)"},
                "tool_result": {"success": True, "stdout": huge_stdout, "figures": []},
            }],
        }
    ]
    resp = client.post("/api/export/report/from-chat", json={"messages": msgs, "title": "t"})
    assert resp.status_code == 200
    body = resp.text

    # Leading lines must be preserved
    assert "line 0" in body
    assert "line 1" in body
    # Trailing lines must be preserved
    assert "line 4999" in body
    # Middle lines must not all be dumped (must not contain "line 2500")
    assert "line 2500" not in body
    # A truncation marker must be present
    assert "lines truncated" in body
    # Total length must be less than the raw 5000-line output
    assert len(body) < 5000  # 30 head + 5 tail + frame ≪ 5000 lines raw


def test_html_export_is_self_contained_and_includes_figures() -> None:
    """New HTML export: a self-contained .html file viewable by double-click, all figures
    embedded as base64, printable to PDF via Ctrl+P. No external CSS / JS / image dependencies."""
    client = _client()
    resp = client.post(
        "/api/export/report/html-from-chat",
        json={"messages": _sample_messages_with_figure(), "title": "Pleiades"},
    )
    assert resp.status_code == 200
    assert resp.headers["content-type"].startswith("text/html")
    body = resp.text

    # HTML structure
    assert "<!DOCTYPE html>" in body
    assert '<html lang="en">' in body
    assert "<title>Pleiades</title>" in body

    # Inline CSS, no external links
    assert "<style>" in body
    assert 'href="http' not in body  # no external links
    assert '<link rel="stylesheet"' not in body  # no external CSS
    assert "<script src=" not in body  # no external JS

    # Figures must be embedded as <img src="data:image/png;base64,...">
    assert 'src="data:image/png;base64,' in body
    assert _TINY_PNG_B64 in body

    # User / Assistant labels
    assert "🧑 You" in body or "You" in body
    assert "🤖 AI Assistant" in body or "AI Assistant" in body


def test_html_export_escapes_user_content_to_prevent_xss() -> None:
    """<script> tags in user input must be escaped and cannot land as executable JS."""
    client = _client()
    msgs = [{"role": "user", "content": "<script>alert(1)</script>"}]
    resp = client.post("/api/export/report/html-from-chat", json={"messages": msgs, "title": "t"})
    assert resp.status_code == 200
    body = resp.text
    # Raw form must not appear
    assert "<script>alert(1)</script>" not in body
    # Escaped form must appear
    assert "&lt;script&gt;" in body


def test_html_export_includes_table_of_contents() -> None:
    """HTML export for long sessions should include a table of contents (one chapter per user message)."""
    client = _client()
    msgs = [
        {"role": "user", "content": "First question about Gaia"},
        {"role": "assistant", "content": "answer 1"},
        {"role": "user", "content": "Second question about TESS"},
        {"role": "assistant", "content": "answer 2"},
    ]
    resp = client.post("/api/export/report/html-from-chat", json={"messages": msgs, "title": "t"})
    assert resp.status_code == 200
    body = resp.text
    assert '<nav class="toc">' in body
    assert "First question about Gaia" in body
    assert "Second question about TESS" in body
    # Each user section must have an anchor id
    assert 'id="turn-0"' in body
    assert 'id="turn-2"' in body


def test_notebook_export_no_figures_still_emits_clean_cell() -> None:
    """A run_python with no figures or stdout must not create an empty outputs array that implies the cell ran."""
    client = _client()
    msgs = [
        {
            "role": "assistant",
            "content": "x",
            "actions": [{
                "action": "run_python",
                "tool_input": {"code": "x = 1"},
                "tool_result": {"success": True, "figures": [], "stdout": ""},
            }],
        }
    ]
    resp = client.post("/api/export/notebook/from-chat", json={"messages": msgs, "title": "t"})
    assert resp.status_code == 200
    nb = json.loads(resp.text)
    code_cells = [c for c in nb["cells"] if c["cell_type"] == "code" and c["source"] == ["x = 1"]]
    assert len(code_cells) == 1
    cell = code_cells[0]
    assert cell["outputs"] == []
    # Without outputs, execution_count stays None (not pretending the cell ran)
    assert cell["execution_count"] is None
